### PR TITLE
static: fix infinite redirection when prefix is set

### LINKED ISSUE #201: Infinite redirect with Prefix in StaticOptions
It looks as though #199 introduced a bug causing an infinite redirect when using `StaticOptions.Prefix`. This issue is around `path.Clean` and passing in `ctx.req.URL.Path`. I think this should be checked against `opt.Prefix` rather than "/" but this requires a special case when `opt.Prefix == ""` which is the fault.

Minimal example:
```go
package main

import (
        "gopkg.in/macaron.v1"
        "net/http"
)

func main() {
        m := macaron.New()
        m.Use(macaron.Static("public", macaron.StaticOptions{
                Prefix: "/public",
        }))
        srv := &http.Server{
                Addr:    "0.0.0.0:8000",
                Handler: m,
        }
        srv.ListenAndServe()
}
```
Put an `index.html` in the `public` directory and navigate to `http://127.0.0.1:8000/public` you should get served the index.html but instead will get an infinite redirect to `/public/`.

### PR DESCRIPTION
**Pull request by humaidq**
This resolves the infinite redirection bug when viewing an index in a static files directory, as `path.Clean` removes the trailing slash. Fixes #201.  
This is mostly a hack on top of `path.Clean`, as we are re-adding the trailing slash.

### CODE REVIEW

File: static.go [hunk 1]
```diff
@@ -150,6 +150,9 @@ func staticHandler(ctx *Context, log *log.Logger, opt StaticOptions) bool {
 	if fi.IsDir() {
 		// Redirect if missing trailing slash.
 		redirPath := path.Clean(ctx.Req.URL.Path)
+		if strings.HasSuffix(ctx.Req.URL.Path, "/") {
+			redirPath = redirPath + "/"
+		}
 		if !strings.HasSuffix(redirPath, "/") {
```
Comment (unknwon) [inline static.go:156]:
```suggestion
		redirPath := path.Clean(ctx.Req.URL.Path)
		// path.Clean removes the trailing slash, so we need to add it back when
		// the original path has it.
		if strings.HasSuffix(ctx.Req.URL.Path, "/") {
			redirPath = redirPath + "/"
		}
		// Redirect if missing trailing slash.
		if !strings.HasSuffix(redirPath, "/") {
```

**Comment by unknwon** [comment]
`v1.3.9` is tagged for this https://github.com/go-macaron/macaron/releases/tag/v1.3.9
